[workspace]
resolver = "2"
members = [
    "crates/nexos-abi",
    "crates/nexos-runtime",
    "crates/nexos-storage",
    "crates/nexos-usb",
    "crates/nexos-userspace",
    "crates/nexfs",
    "kernel",
    "tools/nexos-installer",
    "tools/nexosctl",
    "userspace/nexsh",
]
default-members = [
    "crates/nexos-abi",
    "crates/nexos-runtime",
    "crates/nexos-storage",
    "crates/nexos-usb",
    "crates/nexos-userspace",
    "crates/nexfs",
    "tools/nexos-installer",
    "tools/nexosctl",
]

[workspace.package]
version = "0.14.0-dev"
edition = "2024"
license = "MIT"
authors = ["Emilijus"]
repository = "https://github.com/Emilijus/NexOS"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
